### ISSUE TITLE
`conn->shutdown()`後に`send()`しているように見える

### ISSUE THREAD

**Issue by masnagam** [matching/BonDriver_LinuxMirakc#1]
twitterでRSTされるとの記述を見かけたのでソースを確認したのですが，

https://github.com/matching/BonDriver_LinuxMirakc/blob/08ac93d68234f7644cdbec51b7435cf3de14e58b/src/BonDriver_LinuxMirakc.cpp#L401

ここで`shutdown()`して，

https://github.com/matching/BonDriver_LinuxMirakc/blob/08ac93d68234f7644cdbec51b7435cf3de14e58b/src/http_proc.hpp#L250

ここでhalf-closeのsocketに書き込んでしまうように見えます．

この間に`disconnect()`しているように見えないため，`s < 0`は`false`となり，`connect()`されることはないように見えます．

実際に動かして確認したわけではありませんから，上記の私の推測は間違っているかもしれません．その場合はこのissueを閉じてください．

**Comment by matching** [comment]
ソースご確認までいただきありがとうございます。
確認しましたが、shutdown した後にsendすることはなかったです。（わかりづらいソースで恐縮ですが、受信スレッド側がFINを受けてclose・スレッド終了するのを待った後にconnect,sendするようにしています。）

期待している動き：

> スレッド１（制御スレッド）:
>  ①shutdown
>  ②スレッド２終了まで待ち合わせ(pthread_join)
> 
> スレッド２（受信スレッド）
>  ③（shutdownの結果、）通信先からFINを送られてくるのを期待
>  ④ FINが送られてきたら close、スレッド終了
> 
> スレッド２（制御スレッド）:
>  ⑤ socket, connect
> 

とはいえ、recvからECONNRESETとなっているため、strace, tcpdumpを取って確認してみました。

shutdownのタイミングでFINを送信しているのですが、送受信両方向閉じている（SHUT_RDWR）ので、FIN投げた後に受信したパケット（tcpdump：16:54:55.885322）に対してRSTで応答しています。
そのせいでRST自体は受信していないにも関わらず、ECONNRESETのエラーとなっているように見えました。

■制御スレッド（インターフェース側）
`16:54:55.884700 shutdown(14, SHUT_RDWR) = 0
`

■受信スレッド
```
16:54:55.885859 recvfrom(14, "\204\217\216\377\23XgI\306&\365@\5\245\240\20?0\1\311\f\260\320\334\353\343J&\234\374S\312"..., 48128, 0, NULL, NULL) = 34336
16:54:55.886176 recvfrom(14, 0x7fb0000b70, 48128, 0, NULL, NULL) = -1 ECONNRESET (Connection reset by peer)
16:54:55.887167 close(14)  
```

■tcpdump(ECONNRESETになるパターン)
```
16:54:55.884632 IP 【mirakcサーバ】.40772 > 【クライアント】.44072: Flags [.], seq 45249449:45250897, ack 101, win 509, options [nop,nop,TS val 850027526 ecr 3790173117], length 1448
16:54:55.884644 IP 【mirakcサーバ】.40772 > 【クライアント】.44072: Flags [P.], seq 45250897:45252345, ack 101, win 509, options [nop,nop,TS val 850027526 ecr 3790173117], length 1448
16:54:55.884778 IP 【クライアント】.44072 > 【mirakcサーバ】.40772: Flags [F.], seq 101, ack 45252345, win 3276, options [nop,nop,TS val 3790173122 ecr 850027522], length 0
16:54:55.885322 IP 【mirakcサーバ】.40772 > 【クライアント】.44072: Flags [.], seq 45252345:45253793, ack 102, win 509, options [nop,nop,TS val 850027527 ecr 3790173122], length 1448
16:54:55.885411 IP 【クライアント】.44072 > 【mirakcサーバ】.40772: Flags [R], seq 352028815, win 0, length 0
16:54:55.885462 IP 【mirakcサーバ】.40772 > 【クライアント】.44072: Flags [.], seq 45253793:45268273, ack 102, win 509, options [nop,nop,TS val 850027527 ecr 3790173122], length 14480
16:54:55.885500 IP 【クライアント】.44072 > 【mirakcサーバ】.40772: Flags [R], seq 352028815, win 0, length 0
16:54:55.885547 IP 【mirakcサーバ】.40772 > 【クライアント】.44072: Flags [P.], seq 45268273:45276821, ack 102, win 509, options [nop,nop,TS val 850027527 ecr 3790173122], length 8548
16:54:55.885575 IP 【クライアント】.44072 > 【mirakcサーバ】.40772: Flags [R], seq 352028815, win 0, length 0
16:54:55.890716 IP 【クライアント】.43580 > 【mirakcサーバ】.40772: Flags [S], seq 157947732, win 32120, options [mss 1460,sackOK,TS val 3790173128 ecr 0,nop,wscale 7], length 0
16:54:55.890933 IP 【mirakcサーバ】.40772 > 【クライアント】.43580: Flags [S.], seq 1483438622, ack 157947733, win 65160, options [mss 1460,sackOK,TS val 850027533 ecr 3790173128,nop,wscale 7], length 0
16:54:55.890988 IP 【クライアント】.43580 > 【mirakcサーバ】.40772: Flags [.], ack 1, win 251, options [nop,nop,TS val 3790173128 ecr 850027533], length 0
```


■参考：tcpdump(ECONNRESETにならないパターン)
```
17:07:13.058449 IP 【mirakcサーバ】.40772 > 【クライアント】.59410: Flags [P.], seq 6935985:6936101, ack 97, win 509, options [nop,nop,TS val 850764701 ecr 3790910295], length 116
17:07:13.058766 IP 【クライアント】.59410 > 【mirakcサーバ】.40772: Flags [.], ack 6936101, win 6882, options [nop,nop,TS val 3790910296 ecr 850764700], length 0
17:07:13.064226 IP 【クライアント】.59410 > 【mirakcサーバ】.40772: Flags [F.], seq 97, ack 6936101, win 6882, options [nop,nop,TS val 3790910301 ecr 850764700], length 0
17:07:13.065150 IP 【mirakcサーバ】.40772 > 【クライアント】.59410: Flags [F.], seq 6936101, ack 98, win 509, options [nop,nop,TS val 850764707 ecr 3790910301], length 0
17:07:13.065198 IP 【クライアント】.59410 > 【mirakcサーバ】.40772: Flags [.], ack 6936102, win 6882, options [nop,nop,TS val 3790910302 ecr 850764707], length 0
17:07:13.068595 IP 【クライアント】.59412 > 【mirakcサーバ】.40772: Flags [S], seq 109832047, win 32120, options [mss 1460,sackOK,TS val 3790910306 ecr 0,nop,wscale 7], length 0
```

ということで、対応としては、shutdownで送信側だけ閉じる（SHUT_WR）対応をしております。（なお、もともとのご指摘の箇所もわかりづらい判定だったので無条件にconnectするようにしました）
また、基本的にはありえなくなったのでECONNRESETの判定は削除しました。
最後に「mirakcからのRST」ではなかった点、失礼しました。

**Comment by masnagam** [comment]
説明と確認をありがとうございます．`waitForRecvThreadFinish()`の実装内容を見落としていて，不要な指摘だったみたいですね．お手数をおかけして申し訳ありませんでした．

記憶が曖昧だったのでbsd sockets apiのthread-safeについて少し調べてみました．

linuxのmanには明示的な記述は見つかりませんでしたが，

* https://man7.org/linux/man-pages/man2/shutdown.2.html

libcのマニュアルにthread-safeとの記述を見つけました．

* https://www.gnu.org/software/libc/manual/html_node/Closing-a-Socket.html

別スレッドで`recv()`中に`shutdown()`しても問題ないようです．

しかし，`MirakcConnectBase::s`は保護されていないため，例えば，以下の２つが同時に発生することはありそうです．

* `CBonTuner::RecvThread()`での`pThis->conn->disconnect()`
* `CBonTuner::SetChannel()`での`conn->shutdown()`

このケースでは，`s(-1)`に対して`shutdown(s, ..)`が呼び出されたり，`close(s)`と`shutdown(s, ..)`の呼び出し順が前後するだけで実害はなさそうです．すべての箇所を確認したわけではありませんので，もしかしたら良くないケースがあるかもしれません．

過去，mirakcにはtcp切断に関する問題がありました．

* https://github.com/masnagam/rust-case-studies/tree/master/actix-web-streaming-and-tcp-disconnect

利用しているモジュールに問題があり，これを置きかえることをで回避しました．置き換えの際に問題が発生しないことを検証してはいますが，見逃された問題があるかもしれません．もし，mirakcの挙動に不審な点があれば，こちらでも調査しますので，mirakcにissueを登録（日本語でok）していただければと思います．
